    let tWidth = 60;
    const char_up_right = new Image(tWidth,tWidth);
  char_up_right.src = "./images/char_up_right.png"
  const char_up_left = new Image(tWidth,tWidth);
  char_up_left.src = "./images/char_up_left.png"
  const char_down_left = new Image(tWidth,tWidth);
  char_down_left.src = "./images/char_down_left.png"
  const char_down_right = new Image(tWidth,tWidth);
  char_down_right.src = "./images/char_down_right.png"
  const char_left = new Image(tWidth,tWidth);
  char_left.src = "./images/char_left.png"
  const char_right = new Image(tWidth,tWidth);
  char_right.src = "./images/char_right.png"
  const char_up = new Image(tWidth,tWidth);
  char_up.src = "./images/char_up.png"
  const char_down = new Image(tWidth,tWidth);
  char_down.src = "./images/char_down.png"
  const wood = new Image(tWidth,tWidth);
  wood.src = "./images/wood.jpg"
  const grass = new Image(tWidth,tWidth);
  grass.src = "./images/grass.png"
  const soil = new Image(tWidth,tWidth);
  soil.src = "./images/soil.png"
  const rock = new Image(tWidth,tWidth);
  rock.src = "./images/rock.jpg"
  const unselected_inv = new Image(tWidth,tWidth);
  unselected_inv.src = "./images/unselected_inv.png"
  const inv_slot = new Image(tWidth,tWidth);
  inv_slot.src = "./images/inv_slot.png"
  const house1 = new Image(tWidth,tWidth);
  house1.src = "./images/house1.png"
  const house2 = new Image(tWidth,tWidth);
  house2.src = "./images/house2.png"
  const house3 = new Image(tWidth,tWidth);
  house3.src = "./images/house3.png"
  const house4 = new Image(tWidth,tWidth);
  house4.src = "./images/house4.png"
  const house5 = new Image(tWidth,tWidth);
  house5.src = "./images/house5.png"
  const house6 = new Image(tWidth,tWidth);
  house6.src = "./images/house6.png"
  const house7 = new Image(tWidth,tWidth);
  house7.src = "./images/house7.png"
  const house8 = new Image(tWidth,tWidth);
  house8.src = "./images/house8.png"
  const house9 = new Image(tWidth,tWidth);
  house9.src = "./images/house9.png"
  const house10 = new Image(tWidth,tWidth);
  house10.src = "./images/house10.png"
  const house11 = new Image(tWidth,tWidth);
  house11.src = "./images/house11.png"
  const house12 = new Image(tWidth,tWidth);
  house12.src = "./images/house12.png"
  const house13 = new Image(tWidth,tWidth);
  house13.src = "./images/house13.png"
  const house14 = new Image(tWidth,tWidth);
  house14.src = "./images/house14.png"
  const house15 = new Image(tWidth,tWidth);
  house15.src = "./images/house15.png"
  const house16 = new Image(tWidth,tWidth);
  house16.src = "./images/house16.png"
  const house17 = new Image(tWidth,tWidth);
  house17.src = "./images/house17.png"
  const house18 = new Image(tWidth,tWidth);
  house18.src = "./images/house18.png"
  const house19 = new Image(tWidth,tWidth);
  house19.src = "./images/house19.png"
  const house20 = new Image(tWidth,tWidth);
  house20.src = "./images/house20.png"
  const house21 = new Image(tWidth,tWidth);
  house21.src = "./images/house21.png"
  const house22 = new Image(tWidth,tWidth);
  house22.src = "./images/house22.png"
  const house23 = new Image(tWidth,tWidth);
  house23.src = "./images/house23.png"
  const house24 = new Image(tWidth,tWidth);
  house24.src = "./images/house24.png"
  const house25 = new Image(tWidth,tWidth);
  house25.src = "./images/house25.png"
  const grunk1 = new Image(tWidth,tWidth);
  grunk1.src = "./images/grunk1.png"
  const grunk2 = new Image(tWidth,tWidth);
  grunk2.src = "./images/grunk2.png"
  const grunk3 = new Image(tWidth,tWidth);
  grunk3.src = "./images/grunk3.png"
  const grunk4 = new Image(tWidth,tWidth);
  grunk4.src = "./images/grunk4.png"
  const grunk5 = new Image(tWidth,tWidth);
  grunk5.src = "./images/grunk5.png"
  const grunk6 = new Image(tWidth,tWidth);
  grunk6.src = "./images/grunk6.png"
  const grunk7 = new Image(tWidth,tWidth);
  grunk7.src = "./images/grunk7.png"
  const num1 = new Image(tWidth,tWidth);
  num1.src = "./images/num1.png"
  const num2 = new Image(tWidth,tWidth);
  num2.src = "./images/num2.png"
  const num3 = new Image(tWidth,tWidth);
  num3.src = "./images/num3.png"
  const num4 = new Image(tWidth,tWidth);
  num4.src = "./images/num4.png"
  const num5 = new Image(tWidth,tWidth);
  num5.src = "./images/num5.png"
  const num6 = new Image(tWidth,tWidth);
  num6.src = "./images/num6.png"
  const num7 = new Image(tWidth,tWidth);
  num7.src = "./images/num7.png"
  const num8 = new Image(tWidth,tWidth);
  num8.src = "./images/num8.png"
  const num9 = new Image(tWidth,tWidth);
  num9.src = "./images/num9.png"
  const pickaxe = new Image(tWidth,tWidth);
  pickaxe.src = "./images/pickaxe.png"
  const inv_bar = new Image(tWidth,tWidth);
  inv_bar.src = "./images/inv_bar.png"
  const cliff = new Image(tWidth,tWidth);
  cliff.src = "./images/cliff.png"
  const water = new Image(tWidth,tWidth);
  water.src = "./images/water.png"
  const sand = new Image(tWidth,tWidth);
  sand.src = "./images/sand.png"
  const shop_guy = new Image(tWidth,tWidth);
  shop_guy.src = "./images/shop.png"
  const shop_items = new Image(tWidth,tWidth);
  shop_items.src = "./images/shop_items.png"
  const bucket = new Image(tWidth,tWidth);
  bucket.src = "./images/bucket.png"
  const game_over = new Image(tWidth,tWidth);
  game_over.src = "./images/game_over.png"